In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Series包含了一系列值和一系列索引，我們可以使用values和index屬性來訪問它們。

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)#Series是對應型態鍵和一組型態值的結構
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

38332521

In [13]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [14]:
#例如，數據可以是列表或NumPy數組，在這種情況下，索引默認為整數序列：
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
#數據可以是純量，會被重複的填充到指定的索引：
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
#data可以是字典，其中index默認為已排序的字典鍵：
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
#在每種情況下，如果首選不同的結果，則可以顯式設置索引：
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [22]:
df2=pd.DataFrame({'A':1.,
                'B':pd.Timestamp('20170101'),
                'C':pd.Series(1, index=list(range(4)),dtype='float32'),
                'D':np.array([3]*4, dtype='int32'),
                'E':pd.Categorical(["test","train","test","train"]),
                'F':'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
2  1.0 2017-01-01  1.0  3   test  foo
3  1.0 2017-01-01  1.0  3  train  foo

In [24]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [25]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [27]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [28]:
df2.values

array([[1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [29]:
df2.T

,0,1,2,3
A,1,1,1,1
B,2017-01-01 00:00:00,2017-01-01 00:00:00,2017-01-01 00:00:00,2017-01-01 00:00:00
C,1,1,1,1
D,3,3,3,3
E,test,train,test,train
F,foo,foo,foo,foo

In [30]:
# 排序，對於 axis=1 以 row 方向排序 ascending=False 倒排序
print(df2.sort_index(axis=1, ascending=False))

     F      E  D    C          B    A
0  foo   test  3  1.0 2017-01-01  1.0
1  foo  train  3  1.0 2017-01-01  1.0
2  foo   test  3  1.0 2017-01-01  1.0
3  foo  train  3  1.0 2017-01-01  1.0

In [31]:
# 排序，對於 axis=0 以 col 方向反向排序 (ascending=Fals 指定排序方式)
print(df2.sort_index(axis=0, ascending=False))

     A          B    C  D      E    F
3  1.0 2017-01-01  1.0  3  train  foo
2  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
0  1.0 2017-01-01  1.0  3   test  foo

In [32]:
# 排序 sort_values 針對單行的值進行排序
print(df2.sort_values(by='E'))

     A          B    C  D      E    F
0  1.0 2017-01-01  1.0  3   test  foo
2  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
3  1.0 2017-01-01  1.0  3  train  foo

In [34]:
from pandas_datareader import data as web

In [35]:
all_data={} #create a new dict object and named it all_data

In [36]:
for ticker in ['AAPL','IBM','MSFT','GOOG']: 
    all_data[ticker]=web.get_data_yahoo(ticker,'1/1/2010','1/1/2017')

In [37]:
all_data #dict object, key:value (value 資料型別為 DataFrame)

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0
 2010-01-19   30.741428   29.605715   29.761429   30.719999  182501900.0
 2010-01-20   30.792856   29.928572   30.701429   30.247143  153038200.0
 2010-01-21   30.472857   29.601429   30.297142   29.724285  152038600.0
 2010-01-22   29.642857   28.165714   29.540001   28.250000  220441900.0
 2010-01-25   29.242857   28.598572   28.930000   29.010000  266424900.0
 2010-01-26   30.530001   28.940001   29.421429   29.420000  466777500.0
 2010-01-27   30.082857   28.504286   29.549999   29.697144  430642100.0
 2010-01-28   29.357143   28.385714   29.275715   28.469999  293375600.0
 2010-01-29   28.885714   27.178572   28.725714   27.437143  311488100.0
 2010-02-01   28.000000   27.328571   27.481428   27.818571  187469100.0
 2010-02-02   28.045713   27.625713   27.987143   27.980000  174585600.0
 2010-02-03   28.600000   27.774286   27.881428   28.461428  153832000.0
 2010-02-04   28.338572   27.367144   28.104286   27.435715  189413000.0
 2010-02-05   28.000000   27.264286   27.518572   27.922857  212576700.0
 2010-02-08   28.268572   27.714285   27.955715   27.731428  119567700.0
 2010-02-09   28.214285   27.821428   28.059999   28.027143  158221700.0
 2010-02-10   28.085714   27.751429   27.984285   27.874287   92590400.0
 2010-02-11   28.535715   27.722857   27.840000   28.381428  137586400.0
 2010-02-12   28.805714   27.928572   28.301428   28.625713  163867200.0
 ...                ...         ...         ...         ...          ...
 2016-11-17  110.349998  108.830002  109.809998  109.949997   27632000.0
 2016-11-18  110.540001  109.660004  109.720001  110.059998   28428900.0
 2016-11-21  111.989998  110.010002  110.120003  111.730003   29264600.0
 2016-11-22  112.419998  111.400002  111.949997  111.800003   25965500.0
 2016-11-23  111.510002  110.330002  111.360001  111.230003   27426400.0
 2016-11-25  111.870003  110.949997  111.129997  111.790001   11475900.0
 2016-11-28  112.470001  111.389999  111.430000  111.570000   27194000.0
 2016-11-29  112.029999  110.070000  110.779999  111.459999   28528800.0
 2016-11-30  112.199997  110.269997  111.599998  110.519997   36162300.0
 2016-12-01  110.940002  109.029999  110.370003  109.489998   37086900.0
 2016-12-02  110.089996  108.849998  109.169998  109.900002   26528000.0
 2016-12-05  110.029999  108.250000  110.000000  109.110001   34324500.0
 2016-12-06  110.360001  109.190002  109.500000  109.949997   26195500.0
 2016-12-07  111.190002  109.160004  109.260002  111.029999   29998700.0
 2016-12-08  112.430000  110.599998  110.860001  112.120003   27068300.0
 2016-12-09  114.699997  112.309998  112.309998  113.949997   34402600.0
 2016-12-12  115.000000  112.489998  113.290001  113.300003   26374400.0
 2016-12-13  115.919998  113.750000  113.839996  115.190002   43733800.0
 2016-12-14  116.199997  114.980003  115.040001  115.190002   34031800.0
 2016-12-15  116.730003  115.230003  115.379997  115.820000   46524500.0
 2016-12-16  116.500000  115.650002  116.470001  115.970001   44351100.0
 2016-12-19  117.379997  115.750000  115.800003  116.639999   27779400.0
 2016-12-20  117.500000  116.680000  116.739998  116.949997   21425000.0
 2016-12-21  117.400002  116.779999  116.800003  117.059998   23783200.0
 2016-12-22  116.510002  115.639999  116.349998  116.290001   26085900.0
 2016-12-23  116.519997  115.589996  115.589996  116.519997   14249500.0
 2016-12-27  117.800003  116.489998  116.519997  117.260002   18296900.0
 2016-12-28  118.019997  116.199997  117.519997  116.760002   20905900.0
 2016-12-29  117.110001  116.400002  116.449997  116.730003   15039500.0
 2016-12-30  117.199997  115.430000  116.650002  115.820000   30586300.0

              Adj Close
 Date
 2009-12-31   20.159719
 2010-01-04   20.473503
 2010-01-05   20.508902
 2010-01-06   20.182680
 2010-01-07   20.145369
 2010-01-08   20.279305
 2010-01-11   20.100410
 2010-01-12   19.871763
 2010-01-13   20.152065
 2010-01-14   20.035355
 2010-01-15   19.700523
 2010-01-19   20.572037
 2010-01-20   20.255390
 2010-01-21   19.905249
 2010-01-22   18.917973
 2010-01-25   19.426920
 2010-01-26   19.701479
 2010-01-27   19.887072
 2010-01-28   19.065300
 2010-01-29   18.373636
 2010-02-01   18.629066
 2010-02-02   18.737165
 2010-02-03   19.059557
 2010-02-04   18.372683
 2010-02-05   18.698900
 2010-02-08   18.570709
 2010-02-09   18.768732
 2010-02-10   18.666370
 2010-02-11   19.005989
 2010-02-12   19.169575
 ...                ...
 2016-11-17  106.609329
 2016-11-18  106.715996
 2016-11-21  108.335266
 2016-11-22  108.403137
 2016-11-23  107.850449
 2016-11-25  108.393433
 2016-11-28  108.180122
 2016-11-29  108.073463
 2016-11-30  107.162018
 2016-12-01  106.163315
 2016-12-02  106.560860
 2016-12-05  105.794868
 2016-12-06  106.609329
 2016-12-07  107.656517
 2016-12-08  108.713409
 2016-12-09  110.487801
 2016-12-12  109.857559
 2016-12-13  111.690132
 2016-12-14  111.690132
 2016-12-15  112.300980
 2016-12-16  112.446442
 2016-12-19  113.096069
 2016-12-20  113.396652
 2016-12-21  113.503304
 2016-12-22  112.756714
 2016-12-23  112.979713
 2016-12-27  113.697243
 2016-12-28  113.212425
 2016-12-29  113.183334
 2016-12-30  112.300980

 [1763 rows x 6 columns],
 'IBM':                   High         Low        Open       Close      Volume  \
 Date
 2009-12-31  132.850006  130.750000  132.410004  130.899994   4223400.0
 2010-01-04  132.970001  130.850006  131.179993  132.449997   6155300.0
 2010-01-05  131.850006  130.100006  131.679993  130.850006   6841400.0
 2010-01-06  131.490005  129.809998  130.679993  130.000000   5605300.0
 2010-01-07  130.250000  128.910004  129.869995  129.550003   5840600.0
 2010-01-08  130.919998  129.050003  129.070007  130.850006   4197200.0
 2010-01-11  131.059998  128.669998  131.059998  129.479996   5730400.0
 2010-01-12  131.330002  129.000000  129.029999  130.509995   8081500.0
 2010-01-13  131.119995  129.160004  130.389999  130.229996   6455400.0
 2010-01-14  132.710007  129.910004  130.550003  132.309998   7111800.0
 2010-01-15  132.889999  131.089996  132.029999  131.779999   8494400.0
 2010-01-19  134.250000  131.559998  131.630005  134.139999  13916200.0
 2010-01-20  131.149994  128.949997  130.460007  130.250000  15197500.0
 2010-01-21  130.690002  128.059998  130.470001  129.000000   9608600.0
 2010-01-22  128.889999  125.370003  128.669998  125.500000  10088600.0
 2010-01-25  126.889999  125.709999  126.330002  126.120003   5738500.0
 2010-01-26  127.750000  125.410004  125.919998  125.750000   7135300.0
 2010-01-27  126.959999  125.040001  125.820000  126.330002   8719200.0
 2010-01-28  127.040001  123.050003  127.029999  123.750000   9622200.0
 2010-01-29  125.000000  121.900002  124.320000  122.389999  11571200.0
 2010-02-01  124.949997  122.779999  123.230003  124.669998   7242900.0
 2010-02-02  125.809998  123.949997  124.790001  125.529999   5899900.0
 2010-02-03  126.070000  125.070000  125.160004  125.660004   4177100.0
 2010-02-04  125.440002  122.900002  125.190002  123.000000   9126900.0
 2010-02-05  123.720001  121.830002  123.040001  123.519997   8617000.0
 2010-02-08  123.220001  121.739998  123.150002  121.879997   5718500.0
 2010-02-09  124.199997  122.459999  122.650002  123.209999   6044500.0
 2010-02-10  123.650002  122.209999  122.940002  122.809998   5219100.0
 2010-02-11  124.199997  122.059998  122.580002  123.730003   5089000.0
 2010-02-12  124.050003  121.610001  123.010002  124.000000   8017700.0
 ...                ...         ...         ...         ...         ...
 2016-11-17  159.929993  158.850006  159.220001  159.800003   2261200.0
 2016-11-18  160.720001  159.210007  159.800003  160.389999   2981600.0
 2016-11-21  163.000000  160.369995  160.690002  162.770004   4637100.0
 2016-11-22  163.000000  161.949997  163.000000  162.669998   2770800.0
 2016-11-23  162.380005  161.360001  161.940002  161.979996   2252700.0
 2016-11-25  163.190002  161.830002  161.830002  163.139999   1605300.0
 2016-11-28  164.660004  162.699997  163.199997  164.520004   4449400.0
 2016-11-29  164.410004  163.029999  164.000000  163.529999   3148200.0
 2016-11-30  163.800003  162.210007  163.350006  162.220001   4397800.0
 2016-12-01  162.199997  158.300003  161.949997  159.820007   4635700.0
 2016-12-02  160.289993  158.410004  159.000000  160.020004   2740900.0
 2016-12-05  161.149994  159.589996  160.850006  159.839996   3447100.0
 2016-12-06  160.789993  158.929993  160.130005  160.350006   2859000.0
 2016-12-07  165.179993  160.389999  160.600006  164.789993   4435100.0
 2016-12-08  166.000000  164.220001  164.869995  165.360001   3266400.0
 2016-12-09  166.720001  164.600006  165.179993  166.520004   3146900.0
 2016-12-12  166.789993  165.070007  166.720001  165.500000   3392300.0
 2016-12-13  169.949997  165.679993  165.679993  168.289993   5932300.0
 2016-12-14  169.889999  167.449997  168.369995  168.509995   4124200.0
 2016-12-15  169.850006  167.779999  168.009995  168.020004   3388600.0
 2016-12-16  169.110001  166.059998  168.970001  166.729996   6679200.0
 2016-12-19  167.259995  166.000000  166.830002  166.679993   2955900.0
 2016-12-20  168.250000  166.449997  167.490005  167.600006   2174600.0
 2016-12-21  167.940002  165.250000  166.250000  167.330002   3575700.0
 2016-12-22  168.229996  166.580002  167.360001  167.059998   2802600.0
 2016-12-23  167.490005  166.449997  167.000000  166.710007   1699200.0
 2016-12-27  167.979996  166.850006  166.979996  167.139999   1397500.0
 2016-12-28  167.740005  166.000000  167.289993  166.190002   1757500.0
 2016-12-29  166.990005  166.000000  166.020004  166.600006   1594000.0
 2016-12-30  166.699997  165.500000  166.440002  165.990005   2952800.0

              Adj Close
 Date
 2009-12-31  100.460022
 2010-01-04  101.649574
 2010-01-05  100.421654
 2010-01-06   99.769310
 2010-01-07   99.423950
 2010-01-08  100.421654
 2010-01-11   99.370209
 2010-01-12  100.160728
 2010-01-13   99.945816
 2010-01-14  101.542137
 2010-01-15  101.135361
 2010-01-19  102.946564
 2010-01-20   99.961174
 2010-01-21   99.001846
 2010-01-22   96.315765
 2010-01-25   96.791580
 2010-01-26   96.507637
 2010-01-27   96.952751
 2010-01-28   94.972717
 2010-01-29   93.928993
 2010-02-01   95.678764
 2010-02-02   96.338768
 2010-02-03   96.438553
 2010-02-04   94.397118
 2010-02-05   94.796196
 2010-02-08   93.955933
 2010-02-09   94.981209
 2010-02-10   94.672852
 2010-02-11   95.382065
 2010-02-12   95.590210
 ...                ...
 2016-11-17  147.176270
 2016-11-18  147.719650
 2016-11-21  149.911636
 2016-11-22  149.819550
 2016-11-23  149.184067
 2016-11-25  150.252396
 2016-11-28  151.523392
 2016-11-29  150.611603
 2016-11-30  149.405106
 2016-12-01  147.194687
 2016-12-02  147.378891
 2016-12-05  147.213120
 2016-12-06  147.682831
 2016-12-07  151.772064
 2016-12-08  152.297043
 2016-12-09  153.365402
 2016-12-12  152.425980
 2016-12-13  154.995590
 2016-12-14  155.198196
 2016-12-15  154.746918
 2016-12-16  153.558807
 2016-12-19  153.512756
 2016-12-20  154.360107
 2016-12-21  154.111435
 2016-12-22  153.862762
 2016-12-23  153.540405
 2016-12-27  153.936432
 2016-12-28  153.061478
 2016-12-29  153.439072
 2016-12-30  152.877274

 [1763 rows x 6 columns],
 'MSFT':                  High        Low       Open      Close       Volume  Adj Close
 Date
 2009-12-31  30.990000  30.480000  30.980000  30.480000   31929700.0  24.345514
 2010-01-04  31.100000  30.590000  30.620001  30.950001   38409100.0  24.720928
 2010-01-05  31.100000  30.639999  30.850000  30.959999   49749600.0  24.728914
 2010-01-06  31.080000  30.520000  30.879999  30.770000   58182400.0  24.577150
 2010-01-07  30.700001  30.190001  30.629999  30.450001   50559700.0  24.321552
 2010-01-08  30.879999  30.240000  30.280001  30.660000   51197400.0  24.489288
 2010-01-11  30.760000  30.120001  30.709999  30.270000   68754700.0  24.177786
 2010-01-12  30.400000  29.910000  30.150000  30.070000   65912100.0  24.018032
 2010-01-13  30.520000  30.010000  30.260000  30.350000   51863500.0  24.241684
 2010-01-14  31.100000  30.260000  30.309999  30.959999   63228100.0  24.728914
 2010-01-15  31.240000  30.709999  31.080000  30.860001   79913200.0  24.649038
 2010-01-19  31.240000  30.680000  30.750000  31.100000   46575700.0  24.840738
 2010-01-20  30.940001  30.309999  30.809999  30.590000   54849500.0  24.433378
 2010-01-21  30.719999  30.000000  30.610001  30.010000   73086700.0  23.970112
 2010-01-22  30.200001  28.840000  30.000000  28.959999  102004600.0  23.131437
 2010-01-25  29.660000  29.100000  29.240000  29.320000   63373000.0  23.418983
 2010-01-26  29.850000  29.090000  29.200001  29.500000   66639900.0  23.562756
 2010-01-27  29.820000  29.020000  29.350000  29.670000   63949500.0  23.698549
 2010-01-28  29.870001  28.889999  29.840000  29.160000  117513700.0  23.291180
 2010-01-29  29.920000  27.660000  29.900000  28.180000  193888500.0  22.508421
 2010-02-01  28.480000  27.920000  28.389999  28.410000   85931100.0  22.692129
 2010-02-02  28.500000  28.139999  28.370001  28.459999   54413700.0  22.732069
 2010-02-03  28.790001  28.120001  28.260000  28.629999   61397900.0  22.867855
 2010-02-04  28.500000  27.809999  28.379999  27.840000   77850000.0  22.236853
 2010-02-05  28.280001  27.570000  28.000000  28.020000   80960100.0  22.380629
 2010-02-08  28.080000  27.570000  28.010000  27.719999   52820600.0  22.141001
 2010-02-09  28.340000  27.750000  27.969999  28.010000   59195800.0  22.372641
 2010-02-10  28.240000  27.840000  28.030001  27.990000   48591300.0  22.356657
 2010-02-11  28.400000  27.700001  27.930000  28.120001   65993700.0  22.460506
 2010-02-12  28.059999  27.580000  27.809999  27.930000   81117200.0  22.308741
 ...               ...        ...        ...        ...          ...        ...
 2016-11-17  60.950001  59.970001  60.410000  60.639999   32132700.0  58.306213
 2016-11-18  61.139999  60.299999  60.779999  60.349998   27686300.0  58.027370
 2016-11-21  60.970001  60.419998  60.500000  60.860001   19652600.0  58.517738
 2016-11-22  61.259998  60.810001  60.980000  61.119999   23206700.0  58.767731
 2016-11-23  61.099998  60.250000  61.009998  60.400002   21847200.0  58.075451
 2016-11-25  60.529999  60.130001  60.299999  60.529999    8409600.0  58.200436
 2016-11-28  61.020000  60.209999  60.340000  60.610001   20732600.0  58.277363
 2016-11-29  61.410000  60.520000  60.650002  61.090000   22366700.0  58.738884
 2016-11-30  61.180000  60.220001  60.860001  60.259998   34655400.0  57.940830
 2016-12-01  60.150002  58.939999  60.110001  59.200001   34542100.0  56.921623
 2016-12-02  59.470001  58.799999  59.080002  59.250000   25515700.0  56.969700
 2016-12-05  60.590000  59.560001  59.700001  60.220001   23552700.0  57.902378
 2016-12-06  60.459999  59.799999  60.430000  59.950001   19907000.0  57.642761
 2016-12-07  61.380001  59.799999  60.009998  61.369999   30809000.0  59.008118
 2016-12-08  61.580002  60.840000  61.299999  61.009998   21220800.0  58.661968
 2016-12-09  61.990002  61.130001  61.180000  61.970001   27349400.0  59.585018
 2016-12-12  62.299999  61.720001  61.820000  62.169998   20198100.0  59.777321
 2016-12-13  63.419998  62.240002  62.500000  62.980000   35718900.0  60.556149
 2016-12-14  63.450001  62.529999  63.000000  62.680000   30352700.0  60.267696
 2016-12-15  63.150002  62.299999  62.700001  62.580002   27669900.0  60.171543
 2016-12-16  62.950001  62.119999  62.950001  62.299999   42204700.0  59.902313
 2016-12-19  63.770000  62.419998  62.560001  63.619999   34338200.0  61.171520
 2016-12-20  63.799999  63.029999  63.689999  63.540001   26028400.0  61.094597
 2016-12-21  63.700001  63.119999  63.430000  63.540001   17096300.0  61.094597
 2016-12-22  64.099998  63.410000  63.840000  63.549999   22176600.0  61.104214
 2016-12-23  63.540001  62.799999  63.450001  63.240002   12398000.0  60.806145
 2016-12-27  64.070000  63.209999  63.209999  63.279999   11763200.0  60.844601
 2016-12-28  63.400002  62.830002  63.400002  62.990002   14653300.0  60.565762
 2016-12-29  63.200001  62.730000  62.860001  62.900002   10181600.0  60.479229
 2016-12-30  62.990002  62.029999  62.959999  62.139999   25579900.0  59.748470

 [1763 rows x 6 columns],
 'GOOG':                   High         Low        Open       Close      Volume  \
 Date
 2009-12-31  310.679321  307.986847  310.356445  307.986847   2455400.0
 2010-01-04  312.721039  310.103088  311.449310  311.349976   3937800.0
 2010-01-05  311.891449  308.761810  311.563568  309.978882   6048500.0
 2010-01-06  310.907837  301.220856  310.907837  302.164703   8009000.0
 2010-01-07  303.029083  294.410156  302.731018  295.130463  12912000.0
 2010-01-08  299.675903  292.651581  294.087250  299.064880   9509900.0
 2010-01-11  300.276978  295.100647  300.276978  298.612823  14519600.0
 2010-01-12  297.147339  292.100159  296.893982  293.332153   9769600.0
 2010-01-13  292.288940  285.095734  286.382355  291.648102  13077600.0
 2010-01-14  295.180145  289.521942  290.063416  293.019196   8535300.0
 2010-01-15  294.862213  287.152344  294.752930  288.126007  10939600.0
 2010-01-19  293.302338  286.283020  288.722137  291.911407   8689500.0
 2010-01-20  291.096710  285.786224  291.096710  288.329681   6543600.0
 2010-01-21  291.513977  284.276062  289.834900  289.606384  12697400.0
 2010-01-22  283.456390  265.701874  280.426086  273.227905  13689200.0
 2010-01-25  273.163330  266.024780  271.528961  268.255249   8897200.0
 2010-01-26  273.024231  266.412231  267.246826  269.457428   8767600.0
 2010-01-27  272.055542  265.925415  268.886169  269.298462   7980200.0
 2010-01-28  271.732635  263.585632  270.485748  265.418701   6500100.0
 2010-01-29  268.747070  261.106750  267.505127  263.257751   8334700.0
 2010-02-01  266.173798  263.436584  265.572693  264.787811   4530800.0
 2010-02-02  265.751556  262.100281  265.751556  263.843964   8245600.0
 2010-02-03  269.298462  262.408295  262.626862  268.662598   6037000.0
 2010-02-04  267.261719  261.081909  266.764954  261.687958   6799200.0
 2010-02-05  265.026245  259.541931  262.492737  263.928406   6353000.0
 2010-02-08  269.248810  264.047638  264.529480  265.011353   5423500.0
 2010-02-09  269.015320  265.806183  268.026733  266.486755   5675700.0
 2010-02-10  267.157410  262.140045  265.309418  265.498199   5383700.0
 2010-02-11  268.498688  263.039185  264.936829  266.466888   4851300.0
 2010-02-12  266.839478  263.535950  264.762970  264.837494   4589000.0
 ...                ...         ...         ...         ...         ...
 2016-11-17  772.700012  764.229980  766.919983  771.229980   1304000.0
 2016-11-18  775.000000  760.000000  771.369995  760.539978   1547100.0
 2016-11-21  769.700012  760.599976  762.609985  769.200012   1330600.0
 2016-11-22  776.960022  767.000000  772.630005  768.270020   1593100.0
 2016-11-23  768.283020  755.250000  767.729980  760.989990   1477400.0
 2016-11-25  765.000000  760.520020  764.260010  761.679993    587400.0
 2016-11-28  779.530029  759.799988  760.000000  768.239990   2188200.0
 2016-11-29  778.500000  768.239990  771.530029  770.840027   1616600.0

In [38]:
all_data['AAPL']

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2009-12-31,30.478571,30.080000,30.447144,30.104286,88102700.0,20.159719
2010-01-04,30.642857,30.340000,30.490000,30.572857,123432400.0,20.473503
2010-01-05,30.798571,30.464285,30.657143,30.625713,150476200.0,20.508902
2010-01-06,30.747143,30.107143,30.625713,30.138571,138040000.0,20.182680
2010-01-07,30.285715,29.864286,30.250000,30.082857,119282800.0,20.145369
2010-01-08,30.285715,29.865715,30.042856,30.282858,111902700.0,20.279305
2010-01-11,30.428572,29.778572,30.400000,30.015715,115557400.0,20.100410
2010-01-12,29.967142,29.488571,29.884285,29.674286,148614900.0,19.871763
2010-01-13,30.132856,29.157143,29.695715,30.092857,151473000.0,20.152065
2010-01-14,30.065714,29.860001,30.015715,29.918571,108223500.0,20.035355
2010-01-15,30.228571,29.410000,30.132856,29.418571,148516900.0,19.700523
2010-01-19,30.741428,29.605715,29.761429,30.719999,182501900.0,20.572037
2010-01-20,30.792856,29.928572,30.701429,30.247143,153038200.0,20.255390
2010-01-21,30.472857,29.601429,30.297142,29.724285,152038600.0,19.905249
2010-01-22,29.642857,28.165714,29.540001,28.250000,220441900.0,18.917973
2010-01-25,29.242857,28.598572,28.930000,29.010000,266424900.0,19.426920
2010-01-26,30.530001,28.940001,29.421429,29.420000,466777500.0,19.701479
2010-01-27,30.082857,28.504286,29.549999,29.697144,430642100.0,19.887072
2010-01-28,29.357143,28.385714,29.275715,28.469999,293375600.0,19.065300
2010-01-29,28.885714,27.178572,28.725714,27.437143,311488100.0,18.373636
2010-02-01,28.000000,27.328571,27.481428,27.818571,187469100.0,18.629066
2010-02-02,28.045713,27.625713,27.987143,27.980000,174585600.0,18.737165
2010-02-03,28.600000,27.774286,27.881428,28.461428,153832000.0,19.059557
2010-02-04,28.338572,27.367144,28.104286,27.435715,189413000.0,18.372683
2010-02-05,28.000000,27.264286,27.518572,27.922857,212576700.0,18.698900
2010-02-08,28.268572,27.714285,27.955715,27.731428,119567700.0,18.570709
2010-02-09,28.214285,27.821428,28.059999,28.027143,158221700.0,18.768732
2010-02-10,28.085714,27.751429,27.984285,27.874287,92590400.0,18.666370
2010-02-11,28.535715,27.722857,27.840000,28.381428,137586400.0,19.005989
2010-02-12,28.805714,27.928572,28.301428,28.625713,163867200.0,19.169575
...,...,...,...,...,...,...
2016-11-17,110.349998,108.830002,109.809998,109.949997,27632000.0,106.609329
2016-11-18,110.540001,109.660004,109.720001,110.059998,28428900.0,106.715996
2016-11-21,111.989998,110.010002,110.120003,111.730003,29264600.0,108.335266
2016-11-22,112.419998,111.400002,111.949997,111.800003,25965500.0,108.403137
2016-11-23,111.510002,110.330002,111.360001,111.230003,27426400.0,107.850449
2016-11-25,111.870003,110.949997,111.129997,111.790001,11475900.0,108.393433
2016-11-28,112.470001,111.389999,111.430000,111.570000,27194000.0,108.180122
2016-11-29,112.029999,110.070000,110.779999,111.459999,28528800.0,108.073463
2016-11-30,112.199997,110.269997,111.599998,110.519997,36162300.0,107.162018
2016-12-01,110.940002,109.029999,110.370003,109.489998,37086900.0,106.163315
2016-12-02,110.089996,108.849998,109.169998,109.900002,26528000.0,106.560860
2016-12-05,110.029999,108.250000,110.000000,109.110001,34324500.0,105.794868
2016-12-06,110.360001,109.190002,109.500000,109.949997,26195500.0,106.609329
2016-12-07,111.190002,109.160004,109.260002,111.029999,29998700.0,107.656517
2016-12-08,112.430000,110.599998,110.860001,112.120003,27068300.0,108.713409
2016-12-09,114.699997,112.309998,112.309998,113.949997,34402600.0,110.487801
2016-12-12,115.000000,112.489998,113.290001,113.300003,26374400.0,109.857559
2016-12-13,115.919998,113.750000,113.839996,115.190002,43733800.0,111.690132
2016-12-14,116.199997,114.980003,115.040001,115.190002,34031800.0,111.690132
2016-12-15,116.730003,115.230003,115.379997,115.820000,46524500.0,112.300980
2016-12-16,116.500000,115.650002,116.470001,115.970001,44351100.0,112.446442
2016-12-19,117.379997,115.750000,115.800003,116.639999,27779400.0,113.096069
2016-12-20,117.500000,116.680000,116.739998,116.949997,21425000.0,113.396652
2016-12-21,117.400002,116.779999,116.800003,117.059998,23783200.0,113.503304
2016-12-22,116.510002,115.639999,116.349998,116.290001,26085900.0,112.756714
2016-12-23,116.519997,115.589996,115.589996,116.519997,14249500.0,112.979713
2016-12-27,117.800003,116.489998,116.519997,117.260002,18296900.0,113.697243
2016-12-28,118.019997,116.199997,117.519997,116.760002,20905900.0,113.212425
2016-12-29,117.110001,116.400002,116.449997,116.730003,15039500.0,113.183334
2016-12-30,117.199997,115.430000,116.650002,115.820000,30586300.0,112.300980

In [39]:
all_data['GOOG']

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2009-12-31,310.679321,307.986847,310.356445,307.986847,2455400.0,307.986847
2010-01-04,312.721039,310.103088,311.449310,311.349976,3937800.0,311.349976
2010-01-05,311.891449,308.761810,311.563568,309.978882,6048500.0,309.978882
2010-01-06,310.907837,301.220856,310.907837,302.164703,8009000.0,302.164703
2010-01-07,303.029083,294.410156,302.731018,295.130463,12912000.0,295.130463
2010-01-08,299.675903,292.651581,294.087250,299.064880,9509900.0,299.064880
2010-01-11,300.276978,295.100647,300.276978,298.612823,14519600.0,298.612823
2010-01-12,297.147339,292.100159,296.893982,293.332153,9769600.0,293.332153
2010-01-13,292.288940,285.095734,286.382355,291.648102,13077600.0,291.648102
2010-01-14,295.180145,289.521942,290.063416,293.019196,8535300.0,293.019196
2010-01-15,294.862213,287.152344,294.752930,288.126007,10939600.0,288.126007
2010-01-19,293.302338,286.283020,288.722137,291.911407,8689500.0,291.911407
2010-01-20,291.096710,285.786224,291.096710,288.329681,6543600.0,288.329681
2010-01-21,291.513977,284.276062,289.834900,289.606384,12697400.0,289.606384
2010-01-22,283.456390,265.701874,280.426086,273.227905,13689200.0,273.227905
2010-01-25,273.163330,266.024780,271.528961,268.255249,8897200.0,268.255249
2010-01-26,273.024231,266.412231,267.246826,269.457428,8767600.0,269.457428
2010-01-27,272.055542,265.925415,268.886169,269.298462,7980200.0,269.298462
2010-01-28,271.732635,263.585632,270.485748,265.418701,6500100.0,265.418701
2010-01-29,268.747070,261.106750,267.505127,263.257751,8334700.0,263.257751
2010-02-01,266.173798,263.436584,265.572693,264.787811,4530800.0,264.787811
2010-02-02,265.751556,262.100281,265.751556,263.843964,8245600.0,263.843964
2010-02-03,269.298462,262.408295,262.626862,268.662598,6037000.0,268.662598
2010-02-04,267.261719,261.081909,266.764954,261.687958,6799200.0,261.687958
2010-02-05,265.026245,259.541931,262.492737,263.928406,6353000.0,263.928406
2010-02-08,269.248810,264.047638,264.529480,265.011353,5423500.0,265.011353
2010-02-09,269.015320,265.806183,268.026733,266.486755,5675700.0,266.486755
2010-02-10,267.157410,262.140045,265.309418,265.498199,5383700.0,265.498199
2010-02-11,268.498688,263.039185,264.936829,266.466888,4851300.0,266.466888
2010-02-12,266.839478,263.535950,264.762970,264.837494,4589000.0,264.837494
...,...,...,...,...,...,...
2016-11-17,772.700012,764.229980,766.919983,771.229980,1304000.0,771.229980
2016-11-18,775.000000,760.000000,771.369995,760.539978,1547100.0,760.539978
2016-11-21,769.700012,760.599976,762.609985,769.200012,1330600.0,769.200012
2016-11-22,776.960022,767.000000,772.630005,768.270020,1593100.0,768.270020
2016-11-23,768.283020,755.250000,767.729980,760.989990,1477400.0,760.989990
2016-11-25,765.000000,760.520020,764.260010,761.679993,587400.0,761.679993
2016-11-28,779.530029,759.799988,760.000000,768.239990,2188200.0,768.239990
2016-11-29,778.500000,768.239990,771.530029,770.840027,1616600.0,770.840027
2016-11-30,772.989990,754.830017,770.070007,758.039978,2392900.0,758.039978
2016-12-01,759.849976,737.025024,757.440002,747.919983,3017900.0,747.919983
2016-12-02,754.000000,743.099976,744.590027,750.500000,1452500.0,750.500000
2016-12-05,763.900024,752.900024,757.710022,762.520020,1394200.0,762.520020
2016-12-06,768.830017,757.340027,764.729980,759.109985,1690700.0,759.109985
2016-12-07,771.359985,755.799988,761.000000,771.190002,1761000.0,771.190002
2016-12-08,778.179993,767.229980,772.479980,776.419983,1488100.0,776.419983
2016-12-09,789.429993,779.020996,780.000000,789.289978,1821900.0,789.289978
2016-12-12,791.250000,784.354980,785.039978,789.270020,2104100.0,789.270020
2016-12-13,804.380005,793.340027,793.900024,796.099976,2145200.0,796.099976
2016-12-14,804.000000,794.010010,797.400024,797.070007,1704200.0,797.070007
2016-12-15,803.000000,792.919983,797.340027,797.849976,1626500.0,797.849976
2016-12-16,800.856018,790.289978,800.400024,790.799988,2428300.0,790.799988
2016-12-19,797.659973,786.270020,790.219971,794.200012,1232100.0,794.200012
2016-12-20,798.650024,793.270020,796.760010,796.419983,951000.0,796.419983
2016-12-21,796.676025,787.099976,795.840027,794.559998,1211300.0,794.559998
2016-12-22,793.320007,788.580017,792.359985,791.260010,972200.0,791.260010
2016-12-23,792.739990,787.280029,790.900024,789.909973,623400.0,789.909973
2016-12-27,797.859985,787.656982,790.679993,791.549988,789100.0,791.549988
2016-12-28,794.229980,783.200012,793.700012,785.049988,1153800.0,785.049988
2016-12-29,785.929993,778.919983,783.330017,782.789978,742200.0,782.789978
2016-12-30,782.780029,770.409973,782.750000,771.820007,1770000.0,771.820007